name: Discord notifier

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, closed]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send message to Discord
        uses: Ilshidur/action-discord@0.0.2
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: |
            ✅ New push to `${{ github.ref_name }}`
            Latest commit: ${{ github.event.head_commit.message }}
            <${{ github.event.compare }}>

